# Generated by Django 6.0.3 on 2026-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='job_profile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job_profile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
