# Generated by Django 6.0.3 on 2026-03-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_field_size_increase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='job_profile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
