# Generated by Django 6.0.3 on 2026-03-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_loginotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginOtp',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
