# Generated by Django 6.0.3 on 2026-03-16 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_loginotp_userinfo_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_type', models.CharField(choices=[('registration', 'Registration'), ('verification', 'Verification')], default='registration', max_length=20)),
                ('verification_type', models.CharField(blank=True, choices=[('email', 'Email'), ('mobile', 'Mobile'), ('login', 'Login')], max_length=10, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TempOtp',
        ),
        migrations.DeleteModel(
            name='VerificationOtp',
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'otp_type'], name='accounts_ot_email_71787c_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'verification_type'], name='accounts_ot_user_id_af9b6e_idx'),
        ),
    ]
